commands:
  load:
    description: "Load and enable a plugin"
    permission: "recraftedcore.loadPlugin"
    usage: "/load <pluginname>"

  unload:
    description: "Unload and disable a plugin"
    permission: "recraftedcore.unload"
    usage: "/unload <pluginname>"

permissions:
  recraftedcore.loadPlugin:
    description: "Lets you load a plugin"
    default: false

  recraftedcore.unload:
    description: "Lets you unload a plugin"
    default: false
