name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2  
      - name: Build Artifacts
        run: ./gradlew build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: DarkModCore
          path: build/libs/*
      
